phy=int(input("enter phy marks"))
chem=int(input("enter the chem marks"))
eng=int(input("enter eng marks"))
maths=int(input("enter the maths marks"))
hindi=int(input("enter hindi marks"))
sum=phy+chem+eng+maths+hindi
print("total mark is=",sum)
average=sum/5
print("average mark is=",average)